# Copyright © 2021 Cask Data, Inc.
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# Note: Any changes to this workflow would be used only after merging into develop
name: Build e2e tests

on:
  push:
    branches: [ merge-check, merge-test ]
  pull_request:
    branches: [ merge-check, merge-test]
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

jobs:
  build:
    runs-on: k8s-runner-e2e

    # We allow builds:
    # 1) When triggered manually
    # 2) When it's a merge into a branch
    # 3) For PRs that are labeled as build and
    #  - It's a code change
    #  - A build label was just added
    # A bit complex, but prevents builds when other labels are manipulated
    if: >
      github.event_name == 'workflow_dispatch'
      || github.event_name == 'push'
      || (contains(github.event.pull_request.labels.*.name, 'build')
         && (github.event.action != 'labeled' || github.event.label.name == 'build')
         )

    steps:
      # Pinned 1.0.0 version
    
      - name: Run required e2e tests
        if: ${{ github.event_name != 'workflow_dispatch' && github.event.pull_request.merged == false}}
        run: >
          echo "run required"
          echo "${{ github.event.action }}"
          echo "${{ github.event_name }}"
          echo "${{ github.event.pull_request.merged }}"
      - name: Run all e2e tests
        if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true}}
        run: >
          echo "run all"
          echo "${{ github.event.action }}"
          echo "${{ github.event_name }}"
          echo "${{ github.event.pull_request.merged }}"

          
